### ISSUE TITLE
Desktop support

### ISSUE THREAD

**Issue by rekire** [nukeolay/display_metrics#2]
Hi your package looks quiet interesting, but I would need to have the support for all the 3 desktop platforms too. Can you support those platforms?

Docs for [Windows](https://learn.microsoft.com/windows-hardware/manufacture/desktop/dpi-related-apis-and-registry-settings?view=windows-11) and for [MacOS](https://developer.apple.com/documentation/coregraphics/1456599-cgdisplayscreensize) however I would not be surprised if you can use the same API as on iOS, but I didn't check it yet. For Linux I found nothing helpful within 5 minutes.

**Comment by nukeolay** [comment]
Hello! Sorry, it took me long time to get back to this plugin. Now I'm working on your request.
I've just released 0.4.0 version on [pub.dev](https://pub.dev/packages/display_metrics).
In 0.4.0 Windows support were added.

**Comment by nukeolay** [comment]
@rekire in 0.6.0 macOS support was added.

**Comment by nukeolay** [comment]
@rekire I've added Linux support, but unfortunately can't test it right now. Can you test it, if I give you a compiled demo app?

**Comment by rekire** [comment]
I have just Linux in VMs so the results might be wrong. Could anyone else check it?

**Comment by nukeolay** [comment]
> I have just Linux in VMs so the results might be wrong. Could anyone else check it?

It would be great if you could test it on your VM. I've tried to test it on Ubuntu with WSL, and I get the correct resolution, but the screen size is wrong, also Linux command line utilities `xrandr` and `xdpyinfo` in WSL give me wrong results too. So I think WSL can't get correct information at all.

**Comment by nukeolay** [comment]
@rekire I've tested it on Ubuntu 24.04.1 LTS and its worked as expected. Didn't test it on other Linux distros, but plugin reads EDID to retrive physical size of the screen, so it must be work well on all other distros.
Published 1.0.0 version of the plugin with Linux support.
Now all desktop platforms are supported, so I'm closing this issue.
