### ISSUE TITLE
Failing test: onMethodCall_getPlatformVersion

### ISSUE THREAD

**Issue by MarkSpit** [nukeolay/display_metrics#6]
Hi,

First, thank you for the great plugin! I noticed that the unit test onMethodCall_getPlatformVersion in the DisplayMetricsPluginTest class is not working as expected. The test checks the getPlatformVersion method and verifies the returned value against the Android version. However, it relies on android.os.Build.VERSION.RELEASE, which always returns null in a test environment.

Since this test does not directly relate to the core functionality of the plugin, I suggest removing it completely to avoid confusion and ensure that the test suite focuses on more relevant test cases.

Thank you for your attention!

**Comment by nukeolay** [comment]
Hello! Thank you, I've just released 0.4.0 version on [pub.dev](https://pub.dev/packages/display_metrics).
In 0.4.0 this issue was fixed, also tests and Windows support were added.
